# version: '3.8'

services:
  elasticsearch:
    container_name: log-centralization-elasticsearch-1
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    container_name: log-centralization-kibana-1
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME_FOR_KIBANA}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD_FOR_KIBANA}
      - ELASTICSEARCH_SERVICE_ACCOUNT_TOKEN=${ELASTICSEARCH_SERVICE_ACCOUNT_TOKEN}
      - ENCRYPTED_SAVED_OBJECTS_ENCRYPTION_KEY=${ENCRYPTED_SAVED_OBJECTS_ENCRYPTION_KEY}
      - REPORTING_ENCRYPTION_KEY=${REPORTING_ENCRYPTION_KEY}
      - SECURITY_ENCRYPTION_KEY=${SECURITY_ENCRYPTION_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_HOST}
    links:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - kibana_data:/usr/share/kibana/data
    networks:
      - elastic

volumes:
  esdata:
    driver: local
  kibana_data:
    driver: local

networks:
  elastic:
    driver: bridge
